[package]
name = "bfcomp"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }
iota = "0.2.3"
lazy_static = "1.5.0"
nom = "7"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[[bin]]
name = "basm"
path = "src/bin/basm.rs"